---

- name: redis | check if redis already installed
  command: which redis
  changed_when: false
  failed_when: false
  register: redis_status

- include_tasks: install_{{ ansible_distribution }}.yml
  when: redis_status.rc != 0
