---

- name: eclipse | check if target eclipse is already installed
  stat: path=/usr/local/bin/eclipse-luna
  register: eclipse_luna_dir

- include: eclipse-luna.yml
  when: not eclipse_luna_dir.stat.exists

- name: eclipse | create symlink to eclipse-luna
  sudo: yes
  file: path=/usr/local/bin/eclipse
        src=/usr/local/bin/eclipse-luna/eclipse
        state=link
  when: not eclipse_luna_dir.stat.exists
