---

- name: skk | be sure uim is installed
  sudo: yes
  apt: name=uim
       state=latest

- name: skk | be sure uim_skk is installed
  sudo: yes
  apt: name=uim-skk
       state=latest

- name: skk | be sure uim-toolbar starts on login
  copy: src=uim-toolbar-gtk.desktop
        dest="{{ USER_HOME_DIR }}/.config/autostart/uim-toolbar-gtk.desktop"
