---

# - include: uim_skk.yml
#   when: ansible_distribution == 'Ubuntu'

- ansible.builtin.include_tasks: ibus_skk.yml
  when: ansible_distribution == 'Ubuntu'

- ansible.builtin.include_tasks: AquaSKK.yml
  when: ansible_distribution == 'MacOSX'
