---

- name: rust | check if rust already installed
  command: bash -lc "which cargo"
  register: cargo
  changed_when: false
  failed_when: false

- name: rust | get rust install script
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/rustup.sh
  when: cargo.stdout == ""

- name: rust | install rust with script
  command: sh /tmp/rustup.sh -y
  when: cargo.stdout == ""


# LSP for rust
- name: check rust-analyzer already installed
  command: bash -lc "which rust-analyzer"
  changed_when: false
  failed_when: false
  register: rust_analyzer

- name: install rust-analyzer
  ansible.builtin.unarchive:
    src: https://github.com/rust-lang/rust-analyzer/releases/latest/download/rust-analyzer-x86_64-unknown-linux-gnu.gz
    dest: ~/.local/bin
    remote_src: yes
    mode: '0755'
  when: rust_analyzer.rc != 0
