---

- name: Check if rust already installed
  ansible.builtin.command: bash -lc "which cargo"
  register: cargo
  changed_when: false
  failed_when: false

- name: Get rust install script
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: /tmp/rustup.sh
    mode: '0644'
  when: cargo.rc != 0

- name: Install rust with script
  ansible.builtin.command: sh /tmp/rustup.sh -y
  when: cargo.rc != 0

- name: Set shell info
  ansible.builtin.set_fact:
    shell_info: "{{ ansible_user_shell | shell_config }}"

- name: Setup rustup path
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/{{ shell_info.rc_file }}"
    regexp: ". \"$HOME/.cargo/env\""
    line: ". \"$HOME/.cargo/env\""

# LSP for rust
- name: Check rust-analyzer already installed
  ansible.builtin.command: bash -lc "rustup component list --installed"
  changed_when: false
  failed_when: false
  register: rustup_component

- name: Install rust-analyzer
  ansible.builtin.command: sh -lc "rustup component add rust-analyzer"
  when: rustup_component.stdout is not search('rust-analyzer')
  register: result
  changed_when: result.stdout is search('installing')
