---

- name: Download tarballs
  get_url:
    url: "https://dl.google.com/go/go{{ GOLANG_VERSION }}.linux-amd64.tar.gz"
    dest: "/tmp/go{{ GOLANG_VERSION }}.linux-amd64.tar.gz"

- name: Check if old go directory exist
  stat:
    path: /usr/local/go
  register: go_dir

- name: Dlete old go if exist
  become: yes
  file:
    path: /usr/local/go
    state: absent
  when: go_dir.stat.exists

- name: Install golang
  become: yes
  unarchive:
    src: /tmp/go{{ GOLANG_VERSION }}.linux-amd64.tar.gz
    dest: /usr/local
    remote_src: yes
