---

# install gore
# REPL for golang
- name: golang | install gore
  shell: /bin/bash -lc "go get github.com/motemen/gore"

# install gocode
# コード補完
- name: install gocode
  shell: /bin/bash -lc "go get github.com/nsf/gocode"

# install pp
# Pretty print for golang
- name: install pp
  shell: /bin/bash -lc "go get github.com/k0kubun/pp"

# install godoc
# command reference library
- name: install godoc
  shell: /bin/bash -lc "go get golang.org/x/tools/cmd/godoc"

# official lint tool for go lang
- name: install golint
  shell: /bin/bash -lc "go get github.com/golang/lint/golint"

# dependnecy manager in vendor
- name: install glide
  shell: /bin/bash -lc "go get github.com/Masterminds/glide"
