---

# install gore
# REPL for golang
- name: golang | install gore
  shell: /bin/bash -lc "go get github.com/motemen/gore"

# install gocode
# コード補完
- name: install gocode
  shell: /bin/bash -lc "go get github.com/nsf/gocode"

# install pp
# Pretty print for golang
- name: install pp
  shell: /bin/bash -lc "go get github.com/k0kubun/pp"

# install godoc
# command reference library
- name: install godoc
  shell: /bin/bash -lc "go get golang.org/x/tools/cmd/godoc"

