---

- include: install_{{ ansible_distribution }}.yml

- include: configure_{{ ansible_distribution }}.yml

- include: install_devtools_{{ ansible_distribution }}.yml
  when: GOLANG_INSTALL_DEVTOOLS
