---

- name: golang | check if golang is installed
  shell: /bin/bash -lc 'which go'
  changed_when: false
  failed_when: false
  register: install_golang

- name: golang | check installed golang version
  shell: /bin/bash -lc 'go version'
  changed_when: false
  failed_when: false
  register: install_golang_version
  when: install_golang.rc == 0

- include_tasks: install_{{ ansible_distribution }}.yml
  when: install_golang.rc != 0 or
        install_golang_version.stdout | regex_replace('go version go(.*) .*', '\\1')
                                      is version(GOLANG_VERSION, '<')

- include_tasks: configure_{{ ansible_distribution }}.yml

- include_tasks: install_devtools.yml
  when: GOLANG_INSTALL_DEVTOOLS
