---

- name: Setup git-completion.bash
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    regexp: "^source .*git-completion.bash$"
    line: "source {{ ansible_user_dir }}/.shell.d/git-completion.bash"

- name: Setup starship
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    regexp: "^eval \"$(starship init bash)\""
    line: "eval \"$(starship init bash)\""

- name: Create starship config file
  ansible.builtin.copy:
    src: starship.toml
    dest: "{{ ansible_user_dir }}/.config/starship.toml"
    mode: '0644'

- name: Setup bash_aliases
  ansible.builtin.copy:
    src: bash_aliases
    dest: "{{ ansible_user_dir }}/.bash_aliases"
    mode: '0644'
