---

- name: shell | setup git-completion.bash
  lineinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    regexp: "^source .*git-completion.bash$"
    line: "source {{ ansible_user_dir }}/.shell.d/git-completion.bash"

