---

- name: Create directory to store extensions if not exist
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.shell.d"
    state: directory
    mode: '0755'

- name: Download and store git-completion.bash
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash"
    dest: "{{ ansible_user_dir }}/.shell.d/git-completion.bash"
    mode: '0644'
