---

- name: Setup alias
  ansible.builtin.include_tasks: setup_alias.yml


- name: Check if starship already installed
  ansible.builtin.command: which starship
  register: starship_installed
  changed_when: false
  failed_when: false

- name: Setup starship
  ansible.builtin.include_tasks: setup_starship.yml
  when: starship_installed.rc != 0
