---

# shellのインストール

# shell拡張のインストール
- name: Install extensions
  ansible.builtin.include_tasks: install_git_extension.yml

# shell設定の適用
- name: Configure bashrc config
  ansible.builtin.include_tasks: configure_bashrc.yml
