---

- name: Setup alias
  ansible.builtin.include_tasks: setup_alias.yml

- name: Setup completion
  ansible.builtin.include_tasks: setup_completion_{{ ansible_distribution }}.yml

- name: Check if starship already installed
  ansible.builtin.command: which starship
  register: starship_installed
  changed_when: false
  failed_when: false

- name: Setup starship
  ansible.builtin.include_tasks: setup_starship.yml
  when: starship_installed.rc != 0

- name: Check if direnv already installed
  ansible.builtin.command: which direnv
  register: direnv_installed
  changed_when: false
  failed_when: false

- name: Setup direnv
  ansible.builtin.include_tasks: setup_direnv.yml
  when: direnv_installed.rc != 0
