---

# shellのインストール

# shell拡張のインストール
- name: Install extensions
  ansible.builtin.include_tasks: install_git_extension.yml

# shell設定の適用
- name: Configure bashrc config
  ansible.builtin.include_tasks: configure_bashrc.yml

- name: Check if starship already installed
  ansible.builtin.command: which starship
  register: starship_installed
  changed_when: false

- name: Setup starship
  ansible.builtin.include_tasks: setup_starship.yml
  when: starship_installed.rc != 0
