---

- name: Set shell info
  ansible.builtin.set_fact:
    shell_info: "{{ ansible_user_shell | shell_config }}"

- name: Setup bash_aliases
  ansible.builtin.blockinfile:
    path: "{{ ansible_user_dir }}/{{ shell_info.rc_file }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK shell"
    block: |
      alias be='bundle exec'

      source <(kubectl completion {{ shell_info.name }})
      alias k='kubectl'
      complete -o default -F __start_kubectl k
