# playbook to setup development environment

- name: "Setup common roles for development"
  hosts: all
  roles:
    - { role: apt, tags: apt, APT_DEVTOOL: true }
    - { role: build-essential, tags: build-essential }
    - { role: git, tags: git, GIT_INSTALLER: 'extra' }
    - { role: shell, tags: shell, SHELL_TYPE: 'bash' }
    - { role: fonts, tags: fonts }
    - { role: nfs-client, tags: nfs-client }
    - { role: docker, tags: docker }
    - { role: aqua, tags: aqua }

- name: "Setup application development environment"
  hosts: webapp
  roles:
    - { role: golang, tags: golang }
    - { role: python, tags: python }
    - { role: ruby, tags: ruby }
    - { role: nodejs, tags: nodejs, NODEJS_MAJOR_VERSION: 14 }
    - { role: yarn, tags: yarn }
    - { role: rust, tags: rust }
    - { role: heroku, tags: heroku }
    - { role: gcloud, tags: gcloud }
    - { role: azure-cli, tags: azure-cli }
    - { role: redis, tags: redis }
    - { role: terraform, tags: terraform }
    - { role: ansible, tags: ansible }

- name: "Setup OS development environment"
  hosts: devos
  roles:
    - { role: build-essential, tags: build-essential }
    - { role: git, tags: git, GIT_INSTALLER: 'extra' }
    - { role: shell, tags: shell, SHELL_TYPE: 'bash' }

- name: "Setup terraform development environment"
  hosts: terraform
  roles:
    - { role: build-essential, tags: build-essential }
    - { role: git, tags: git, GIT_INSTALLER: 'extra' }
    - { role: shell, tags: shell, SHELL_TYPE: 'bash' }
    - { role: golang, tags: golang }
    - { role: docker, tags: docker }
    - { role: terraform, tags: terraform }
    - { role: ansible, tags: ansible }
