# playbook to setup development environment

- hosts: all
  roles:
    - { role: apt, tags: apt, APT_DEVTOOL: true }
    - { role: build-essential, tags: build-essential }
    - { role: git, tags: git, GIT_INSTALLER: 'extra' }
    - { role: shell, tags: shell, SHELL_TYPE: 'bash' }
    - { role: fonts, tags: fonts }
    - { role: nfs-client, tags: nfs-client }
    - { role: docker, tags: docker }
    - { role: github-cli, tags: github-cli }

- hosts: webapp
  roles:
    - { role: golang, tags: golang }
    - { role: gibo, tags: gibo }
    - { role: python, tags: python }
    - { role: ruby, tags: ruby }
    - { role: nodejs, tags: nodejs, NODEJS_MAJOR_VERSION: 14 }
    - { role: yarn, tags: yarn }
    - { role: rust, tags: rust }
    - { role: heroku, tags: heroku }
    - { role: awscli, tags: awscli, AWSCLI_OPTION: 'all' }
    - { role: gcloud, tags: gcloud }
    - { role: azure-cli, tags: azure-cli }
    - { role: kubectl, tags: kubectl }
    - { role: hugo, tags: hugo }
    - { role: redis, tags: redis }
    - { role: terraform, tags: terraform }
    - { role: ansible, tags: ansible }

- hosts: devos
  roles:
    - { role: build-essential, tags: build-essential }
    - { role: git, tags: git, GIT_INSTALLER: 'extra' }
    - { role: shell, tags: shell, SHELL_TYPE: 'bash' }

- hosts: terraform
  roles:
    - { role: build-essential, tags: build-essential }
    - { role: git, tags: git, GIT_INSTALLER: 'extra' }
    - { role: shell, tags: shell, SHELL_TYPE: 'bash' }
    - { role: golang, tags: golang }
    - { role: docker, tags: docker }
    - { role: terraform, tags: terraform }
    - { role: ansible, tags: ansible }
