---

- name: check td-agent already installed
  ansible.builtin.command: which td-agent
  changed_when: false
  failed_when: false
  register: which_tdagent

- name: check td-agent version
  ansible.builtin.command: td-agent --version
  changed_when: false
  failed_when: false
  when: which_tdagent.rc != 0
  register: version_tdagent


- name: download install script
  ansible.builtin.get_url:
    url: https://toolbelt.treasuredata.com/sh/install-ubuntu-{{ ansible_distribution_release }}-td-agent4.sh
    dest: /tmp/install-td-agent4.sh
    mode: '0755'


- name: install td-agent
  become: yes
  ansible.builtin.shell: /tmp/install-td-agent4.sh
