---

- name: awscli | create temp directory to clone repository
  tempfile:
    state: directory
    prefix: awscli-gitsecret-
  register: tmpdir

- name: awscli | clone git-secrets repository
  git:
    repo: https://github.com/awslabs/git-secrets
    dest: "{{ tmpdir.path }}"
    version: 1.2.1

# for Linux
- name: awscli | install git-secrets
  become: yes
  make:
    chdir: "{{ tmpdir.path }}"
    target: install
  when: ansible_system == 'Linux'

# for MacOSX
- name: awscli | install git-secrets
  make:
    chdir: "{{ tmpdir.path }}"
    target: install
  when: ansible_system == 'Darwin'

- name: awscli | create init template for git-secrets
  command: git secrets --install {{ ansible_user_dir }}/.git-templates/git-secrets

- name: awscli | apply git-secrets rules for all init git repositories
  command: git config --global init.templatedir '{{ ansible_user_dir }}/.git-templates/git-secrets'
