---

- name: awscli | clone git-secrets repository
  git:
    repo: https://github.com/awslabs/git-secrets
    dest: /tmp/repos/git-secrets
    version: 1.2.1

- name: awscli | install git-secrets
  become: yes
  make:
    chdir: /tmp/repos/git-secrets
    target: install

- name: awscli | create init template for git-secrets
  command: git secrets --install {{ ansible_user_dir }}/.git-templates/git-secrets

- name: awscli | apply git-secrets rules for all init git repositories
  command: git config --global init.templatedir '{{ ansible_user_dir }}/.git-templates/git-secrets'
