---


- name: download awscli v2
  get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp/awscliv2.zip

- name: unarchive zip
  unarchive:
    src: /tmp/awscliv2.zip
    dest: /tmp/
    remote_src: yes

- name: install awscli v2
  become: yes
  shell: /tmp/aws/install

- name: setup environment variable for pip local bin
  lineinfile:
    dest: "{{ ansible_user_dir }}/.profile"
    regexp: '^export PATH=~/.local/bin:\$PATH'
    line: "export PATH=~/.local/bin:$PATH"
    insertafter: "EOF"


# option: eb_cli
- name: awscli | install aws EB CLI
  pip:
    name: awsebcli
    extra_args: --upgrade --user
  when: AWSCLI_OPTION_AWSEBCLI == 'yes'


# option: ecs_cli
- include_tasks: install_aws_ecs_cli.yml


# option: git-secrets
- name: awscli | check if git-secrets directory exist
  stat:
    path: "{{ ansible_user_dir }}/.git-templates/git-secrets"
  register: result

- include_tasks: install_git_secrets.yml
  when: not result.stat.exists


# option: fargatecli
- name: awscli | check if fargate cli already installed
  command: which fargate
  register: fargatecli_result
  changed_when: false
  failed_when: false

- include_tasks: install_fargatecli.yml
  when: (AWSCLI_OPTION == 'all' and fargatecli_result.rc != 0) or
        (AWSCLI_OPTION == 'select' and AWSCLI_OPTION_FARGATECLI | default(no) == yes and fargatecli_result.rc != 0)
