---


- name: download awscli v2
  get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp/awscliv2.zip

- name: unarchive zip
  unarchive:
    src: /tmp/awscliv2.zip
    dest: /tmp/
    remote_src: yes

- name: check if awscli already installed
  command: which aws
  changed_when: false
  failed_when: false
  register: which_awscli

- name: set awscli install option
  set_fact:
    AWSCLI_INSTALL_OPTION: '--update'
  when: which_awscli.rc == 0

- name: install awscli v2
  become: yes
  shell: /tmp/aws/install {{ AWSCLI_INSTALL_OPTION | default(omit) }}

# option: eb_cli
- name: awscli | install aws EB CLI
  pip:
    name: awsebcli
    extra_args: --upgrade --user
  when: AWSCLI_OPTION == 'all' or AWSCLI_OPTION_AWSEBCLI|default(false)


# option: ecs_cli
- name: include task to install ecs cli
  include_tasks: install_aws_ecs_cli.yml
  when: AWSCLI_OPTION == 'all' or AWSCLI_OPTION_ECS_CLI|default(false)


# option: git-secrets
- name: awscli | check if git-secrets directory exist
  stat:
    path: "{{ ansible_user_dir }}/.git-templates/git-secrets"
  register: result

- include_tasks: install_git_secrets.yml
  when:
    - not result.stat.exists
    - AWSCLI_OPTION == 'all' or AWSCLI_OPTION_GIT_SECRETS|default(false)


# option: fargatecli
- name: awscli | check if fargate cli already installed
  command: which fargate
  register: fargatecli_result
  changed_when: false
  failed_when: false

- include_tasks: install_fargatecli.yml
  when: (AWSCLI_OPTION == 'all' and fargatecli_result.rc != 0) or
        (AWSCLI_OPTION == 'select' and AWSCLI_OPTION_FARGATECLI | default(no) == yes and fargatecli_result.rc != 0)
