---

- name: install awscli
  become: yes
  pip:
    name: awscli
    extra_args: --user

- name: setup environment variable for pip local bin
  lineinfile:
    dest: "{{ ansible_user_dir }}/.profile"
    regexp: "^export PATH=~/.local/bin:$PATH"
    line: "export PATH=~/.local/bin:$PATH"
    insertafter: "EOF"
