---

- name: ssh_hosts | scan remote host public key
  shell: ssh-keyscan -H {{ HOST_NAME }} 2>/dev/null
  register: public_key

- name: ssh_hosts | add public key to known_host
  sudo: yes
  lineinfile: dest=/etc/ssh/ssh_known_hosts
              line="{{ public_key.stdout }}"
