---

- name: clone nodenv into ~/.nodenv
  ansible.builtin.git:
    repo: 'https://github.com/nodenv/nodenv'
    dest: "{{ ansible_env.HOME }}/.nodenv"

- name: add nodenv bin to PATH
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.profile"
    marker: "# {mark} ANSIBLE MANAGED BLOCK for nodenv"
    block: |
      export PATH="$HOME/.nodenv/bin:$PATH"
      eval "$(nodenv init -)"

- name: create nodenv plugin directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.nodenv/plugins"
    state: directory

- name: clone nodenv-build into ~/.nodenv/plugins/
  ansible.builtin.git:
    repo: 'https://github.com/nodenv/node-build'
    dest: "{{ ansible_env.HOME }}/.nodenv/plugins/node-build"

- name: Check nodenv installed version
  ansible.builtin.shell: bash -lc "nodenv version"
  register: nodenv_version
  changed_when: false

- name: Install default node.js
  ansible.builtin.shell: bash -lc "nodenv install {{ NODEJS_VERSION }}"
  when: nodenv_version.stdout is not contains(NODEJS_VERSION)

- name: enable node.js for global
  ansible.builtin.shell: bash -lc "nodenv global {{ NODEJS_VERSION }}"
