---

- name: nodejs | check if nodejs is installed
  shell: which node
  register: node_stat
  changed_when: false
  failed_when: false

- include_tasks: install_{{ ansible_distribution }}.yml
  when: node_stat.rc != 0
