---

- name: maven | install maven
  sudo: yes
  apt: name=maven
       state=latest

- name: maven | configure m2_home
  lineinfile: dest="{{ USER_HOME_DIR }}"/.profile
              line="M2_HOME=/usr/share/maven"
              regexp="^M2_HOME="
