---

- name: intellij | create working directory if not exists
  file: path={{ workdir }}
        state=directory

- name: intellij | download IntelliJ IDEA tarball
  get_url: url=https://download.jetbrains.com/idea/ideaIC-2016.2.3.tar.gz
           dest={{ workdir }}/ideaIC-{{ intellij_ver }}.tar.gz

- name: intellij | unarchive IntelliJ IDEA tarbarll
  unarchive: src={{ workdir }}/ideaIC-{{ intellij_ver }}.tar.gz
             dest={{ workdir }}
             copy=no

- name: intellij | get unarchived direcotory name
  shell: (cd {{ workdir }} && ls -1 | grep -v tar.gz$)
  register: intellij_directory
  changed_when: false

- name: intellij | move unarchived files into install directory
  sudo: yes
  command: mv {{ workdir }}/{{ intellij_directory.stdout }} {{ installdir }}

- name: intellij | change owner to user
  sudo: yes
  file: path={{ installdir }}
        owner={{ USER_NAME }}
        group={{ USER_NAME }}
        recurse=yes
