---

workdir: /tmp/ideaIC-{{ INTELLIJ_VERSION }}

- name: intellij | create working directory if not exists
  file:
    path: {{ workdir }}
    state: directory

- name: intellij | download IntelliJ IDEA tarball
  get_url:
    url: https://download.jetbrains.com/idea/ideaIC-{{ INTELLIJ_VERSION }}.tar.gz
    dest: {{ workdir }}/ideaIC-{{ INTELLIJ_VERSION }}.tar.gz

- name: intellij | unarchive IntelliJ IDEA tarbarll
  unarchive:
    src: {{ workdir }}/ideaIC-{{ INTELLIJ_VERSION }}.tar.gz
    dest: {{ workdir }}
    copy: no

- name: intellij | get unarchived direcotory name
  shell: (cd {{ workdir }} && ls -1 | grep -v tar.gz$)
  register: intellij_directory
  changed_when: false

- name: intellij | move unarchived files into install directory
  become: yes
  command: mv {{ workdir }}/{{ intellij_directory.stdout }} {{ INTELLIJ_INSTALL_DIR }}

- name: intellij | change owner to user
  become: yes
  file:
    path: {{ INTELLIJ_INSTALL_DIR }}
    owner: {{ USER_NAME }}
    group: {{ USER_NAME }}
    recurse: yes
