---

- name: Install python3-venv
  become: yes
  ansible.builtin.apt:
    name: python3-venv

# setup pyenv
# see: https://github.com/pyenv/pyenv

- name: Install pyenv
  ansible.builtin.pip:
    name:
      - pipenv

- name: Install dependencies
  become: yes
  ansible.builtin.apt:
    name: "{{ packages }}"
  vars:
    packages:
      - libbz2-dev
      - liblzma-dev
      - python-tk
      - tk-dev

- name: Setup shell environment for pyenv
  ansible.builtin.blockinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK Pyenv"
    block: |
      export PYENV_ROOT="$HOME/.pyenv"
      export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init - )"
