---

- name: Setup python depends on OS
  ansible.builtin.include_tasks: install_{{ ansible_distribution }}.yml

- name: Setup devtools for python
  ansible.builtin.include_tasks: devtools_{{ ansible_distribution }}.yml
