---

- name: azure-cli | check if azure cli is installed
  command: which az
  changed_when: false
  failed_when: false
  register: azinstall

- include_tasks: install_{{ ansible_distribution }}.yml
  when: azinstall.rc == 1
