---

# install kubectl with aqua. only completion is required.

- name: Set shell info
  ansible.builtin.set_fact:
    shell_info: "{{ ansible_user_shell | shell_config }}"

- name: Apply kubectl completion
  ansible.builtin.lineinfile:
    dest: "{{ ansible_user_dir }}/{{ shell_info.rc_file }}"
    regexp: "^source <\\(kubectl completion {{ shell_info.name }}\\)"
    line: "source <(kubectl completion {{ shell_info.name }})"
    insertafter: "EOF"
