---

- name: R | add gpg key
  become: yes
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: E298A3A825C0D65DFD57CBB651716619E084DAB9

- name: R | add R repository
  become: yes
  template:
    src: r.list.j2
    dest: /etc/apt/sources.list.d/r.list

- name: R | install R lang
  become: yes
  apt:
    name: r-base
    update_cache: yes
