---

- name: openshift-client | download openshift client archive
  get_url:
    url: "{{ OPENSHIFT_CLIENT_RELEASE_URL }}/v{{ OPENSHIFT_VERSION }}/openshift-origin-client-tools-v{{ OPENSHIFT_VERSION }}-{{ OPENSHIFT_CLI_HASH[item] }}-linux-64bit.tar.gz"  # yamllint disable-line rule:line-length
    dest: /tmp/
  with_items:
    - "{{ OPENSHIFT_VERSION }}"


- name: openshift-client | unarchive installer
  unarchive:
    src: "/tmp/openshift-origin-client-tools-v{{ OPENSHIFT_VERSION }}-{{ OPENSHIFT_CLI_HASH[item] }}-linux-64bit.tar.gz"  # yamllint disable-line rule:line-length
    dest: /tmp/
    remote_src: yes
  with_items:
    - "{{ OPENSHIFT_VERSION }}"

- name: openshift-client | copy binary file
  become: yes
  copy:
    src: "/tmp/openshift-origin-client-tools-v{{ OPENSHIFT_VERSION }}-{{ OPENSHIFT_CLI_HASH[item] }}-linux-64bit/oc"  # yamllint disable-line rule:line-length
    dest: /usr/local/bin/
    remote_src: yes
    mode: 0755
  with_items:
    - "{{ OPENSHIFT_VERSION }}"
