---

- name: check if venv is installed
  shell: dpkg -l | grep python3-venv; echo $?
  register: venv_stat
  changed_when: false

# install python3-venv if not installed
- include: install_Ubuntu.yml
  when: venv_stat.stdout == '1'
