---

- name: git | check if git is isntalled
  command: which git >/dev/null; echo $?
  changed_when: false
  register: git_status

- name: git | be sure git is installed
  become: yes
  yum: name=git state=latest
  when: git_status.stdout != '0'
