---

- name: git | be sure git is installed
  homebrew:
    name: git

- name: git | apply git prompt
  blockinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    block: |
      source /usr/local/etc/bash_completion.d/git-prompt.sh
      source /usr/local/etc/bash_completion.d/git-completion.bash
      GIT_PS1_SHOWDIRTYSTATE=true
      GIT_PS1_SHOWUPSTREAM=true

      export PS1='\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w$(__git_ps1 " (%s)")\[\033[00m\]\n\$ '
