---

- name: git | be sure git is installed (using default package repository)
  become: yes
  apt:
    name: git
    state: latest
  when: GIT_INSTALLER == 'package'

- name: git | add PPA for up-to-date version
  become: yes
  apt_repository:
    repo: ppa:git-core/ppa
  when: GIT_INSTALLER == 'extra'

- name: git | be sure git is installed (using ppa)
  become: yes
  apt:
    name: git
    state: latest
    update_cache: yes
  when: GIT_INSTALLER == 'extra'
