---

- name: Create directory to store extensions if not exist
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.shell.d"
    state: directory
    mode: '0755'

- name: Set shell info
  ansible.builtin.set_fact:
    shell_info: "{{ ansible_user_shell | shell_config }}"

- name: Download and store git-completion
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.{{ shell_info.name }}"
    dest: "{{ ansible_user_dir }}/.shell.d/git-completion.{{ shell_info.name }}"
    mode: '0644'

- name: Setup git-completion on rc file
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/{{ shell_info.rc_file }}"
    regexp: "^source .*git-completion"
    line: "source {{ ansible_user_dir }}/.shell.d/git-completion.{{ shell_info.name }}"
