---

- name: java | configure JAVA_HOME
  lineinfile: dest="/home/{{ ansible_env.USER }}/.profile"
              regexp="^JAVA_HOME="
              line="JAVA_HOME=$(readlink -f /usr/bin/javac | sed \"s:bin/javac::\")"

- name: java | add java bin into execute path
  lineinfile: dest="/home/{{ ansible_env.USER }}/.profile"
              line="PATH=$JAVA_HOME/bin:$PATH"
