---

- ansible.builtin.include_tasks: openjdk_lts.yml
  when: ansible_distribution == 'Ubuntu'

- ansible.builtin.include_tasks: JavaForOSX.yml
  when: ansible_distribution == 'MacOSX'

- ansible.builtin.import_tasks: configure.yml
