---

- name: install pip
  become: yes
  apt:
    name: python-pip
  when: ansible_python.version.major == 2

- name: install pip3
  become: yes
  apt:
    name: python3-pip
  when: ansible_python.version.major == 3
