---

- name: build-essentials | be sure build-essential is installed
  become: yes
  apt: name=build-essential
       state=latest

- name: build-essential | install make tools
  become: yes
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - automake
    - make
    - texinfo
    - unzip

- name: build-essentials | enable completion
  include: completion_{{ ansible_distribution }}.yml
