---

- name: Clone tfenv
  ansible.builtin.git:
    repo: https://github.com/tfutils/tfenv
    dest: "{{ ansible_user_dir }}/.tfenv"

- name: Add path
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    regexp: '^export PATH="$HOME/.tfenv/bin:$PATH"'
    line: 'export PATH="$HOME/.tfenv/bin:$PATH"'

- name: Install terraform
  ansible.builtin.command: "{{ ansible_user_dir }}/.tfenv/bin/tfenv install {{ TERRAFORM_VERSION }}"
  register: install_terraform
  changed_when: "'is already installed' not in install_terraform.stdout"

- name: Use specified terraform version
  ansible.builtin.command: "{{ ansible_user_dir }}/.tfenv/bin/tfenv use {{ TERRAFORM_VERSION }}"
  changed_when: false
