---

- name: Install hashicorp official package
  ansible.builtin.include_tasks: official_package.yml

- name: Check if tfenv installed
  ansible.builtin.command: which tfenv
  changed_when: false
  failed_when: false
  register: tfenv_install

- name: Install tfenv
  ansible.builtin.include_tasks: install_tfenv.yml
  when: tfenv_install.rc != 0

- name: Install terraform language server
  become: yes
  ansible.builtin.apt:
    name: terraform-ls
    update_cache: true

- name: Check if tfsec installed
  ansible.builtin.command: which tfsec
  changed_when: false
  failed_when: false
  register: tfsec_install_check

- name: Install tfsec
  # noqa: command-instead-of-shell PATHを反映するためにログインシェルで実行する必要がある
  ansible.builtin.shell: /bin/bash -lc "go install github.com/aquasecurity/tfsec/cmd/tfsec@latest"
  when: tfsec_install_check.rc != 0
  register: install_tfsec
  changed_when: insatll_tfsec.stdout != ""


- name: Check if tflint installed
  ansible.builtin.command: which tflint
  changed_when: false
  failed_when: false
  register: tflint_install

- name: Fetch tflint install script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh
    dest: /tmp/install_tflint_linux.sh
  when: tflint_install.rc != 0

- name: Install tflint
  become: yes
  ansible.builtin.command: bash /tmp/install_tflint_linux.sh
  when: tflint_install.rc != 0
  changed_when: true
