---

- name: terraform | check if terraform is installed
  command: which terraform
  changed_when: false
  failed_when: false
  register: terraform_exist

- name: terraform | check if terraform is specified version
  command: terraform --version
  changed_when: false
  failed_when: false
  register: terraform_version

- include_tasks: install.yml
  when: terraform_version.stdout | regex_replace('.* v(.*)$', '\\1')
                                 is version_compare(TERRAFORM_VERSION, '!=')


- name: terraform | check if terraform-docs is installed
  command: which terraform-docs
  changed_when: false
  failed_when: false
  register: terraform_docs_exist

- include_tasks: install_terraform_docs.yml
  when: terraform_docs_exist.rc != 0


- name: check if tfenv installed
  command: which tfenv
  changed_when: false
  failed_when: false
  register: tfenv_install

- include_tasks: install_tfenv.yml
  when: tfenv_install.rc != 0
