---

- name: Add keyring
  become: yes
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /etc/apt/keyrings/hashicorp-archive-keyring.gpg
    mode: '0644'

- name: Add HashiCorp Repo
  ansible.builtin.template:
    src: hashicorp.list.j2
    dest: /etc/apt/sources.list.d/hashicorp.list
    mode: '0644'
