---

- name: Install ansible
  ansible.builtin.include_tasks: install_{{ ansible_distribution }}.yml

- name: Setup devtools for ansible
  ansible.builtin.include_tasks: devtools_{{ ansible_distribution }}.yml
