---

- name: Add docker gpg key
  become: yes
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add docker apt repository
  become: yes
  ansible.builtin.template:
    src: docker.list.j2
    dest: /etc/apt/sources.list.d/docker.list
    mode: '0644'

- name: Install docker-ce package
  become: yes
  ansible.builtin.apt:
    name: docker-ce
    update_cache: yes

- name: Start docker service
  become: yes
  ansible.builtin.service:
    name: docker
    state: started

# check for require of docker-selinux


- name: Install docker compose plugin
  become: yes
  ansible.builtin.apt:
    name: docker-compose-plugin
