---

- name: docker | add gpg key
  become: yes
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D

- name: docker | add docker repo
  become: yes
  copy:
    src: docker.list.{{ ansible_distribution_release }}
    dest: /etc/apt/sources.list.d/docker.list

- name: docker | install docker engine package
  become: yes
  apt:
    name: docker-engine
    update_cache: yes

- name: docker | start docker
  become: yes
  service:
    name: docker
    state: started

# check for require of docker-selinux
