---

- name: Add docker gpg key
  become: yes
  ansible.builtin.apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D

- name: Add docker repo
  become: yes
  ansible.builtin.copy:
    src: docker.list.{{ ansible_distribution_release }}
    dest: /etc/apt/sources.list.d/docker.list

- name: Install docker engine package
  become: yes
  ansible.builtin.apt:
    name: docker-engine
    update_cache: yes

- name: Start docker service
  become: yes
  ansible.builtin.service:
    name: docker
    state: started

# check for require of docker-selinux
