---

- name: Check if docker installed
  ansible.builtin.command: which docker
  failed_when: false
  changed_when: false
  register: docker_install

- name: Install docker on {{ ansible_distribution }}
  ansible.builtin.include_tasks: install_{{ ansible_distribution }}.yml
  when: docker_install.rc != 0

- name: Configure docker on {{ ansible_distribution }}
  ansible.builtin.include_tasks: configure_{{ ansible_distribution }}.yml
  when: DOCKER_APPLY_CUSTOM|default(false)

- name: Install extra packages for docker
  ansible.builtin.include_tasks: add_library_{{ ansible_distribution }}.yml
  when: DOCKER_APPLY_CUSTOM|default(false)

- name: Add docker user
  become: yes
  ansible.builtin.user:
    name: "{{ DOCKER_USER }}"
    group: docker
