---

# major/minor version for golang
GOLANG_VERSION: 1.16.5

# GOやその他開発用ファイル/リポジトリ置き場
GOLANG_GOPATH: "$HOME"

# GOのPATH設定を記述するファイル
# see: https://golang.org/doc/install
GOLANG_SHELL_INIT_FILE: '.profile'

# 開発に便利なツール群のインストール
GOLANG_INSTALL_DEVTOOLS: yes
