---

- name: dropbox | be sure dropbox is installed
  sudo: yes
  apt: name=nautilus-dropbox

- name: dropbox | check if dropbox is running
  shell: dropbox running; echo $?
  register: running
  changed_when: false
  always_run: yes

- name: dropbox | be sure dropbox is running
  command: dropbox start
  when: running.stdout != '1'

- name: dropbox | check if dropbox autostart on login
  stat: path={{ USER_HOME_DIR }}/.config/autostart/dropbox.desktop
  register: autostart

- name: dropbox | be sure dropbox autostart on login
  command: dropbox autostart y
  when: not autostart.stat.exists