---

- name: english_path | save configure about directory name
  lineinfile: dest={{ ansible_env.HOME }}/.config/user-dirs.dirs
              regexp="{{ item.regexp }}"
              insertafter="{{ item.insertafter }}"
              line="{{ item.line }}"
  with_items:
    # yamllint disable rule:commas
    - { regexp: '^XDG_DESKTOP_DIR',   line: 'XDG_DESKTOP_DIR=\"$HOME/Desktop\"',     insertafter: EOF }
    - { regexp: '^XDG_DOWNLOAD_DIR',  line: 'XDG_DOWNLOAD_DIR=\"$HOME/Download\"',   insertafter: EOF }
    - { regexp: '^XDG_TEMPLATES_DIR', line: 'XDG_TEMPLATES_DIR=\"$HOME/Template\"',  insertafter: EOF }
    - { regexp: '^XDG_PUBLICSHARE',   line: 'XDG_PUBLICSHARE_DIR=\"$HOME/Public\"',  insertafter: EOF }
    - { regexp: '^XDG_DOCUMENTS_DIR', line: 'XDG_DOCUMENTS_DIR=\"$HOME/Documents\"', insertafter: EOF }
    - { regexp: '^XDG_MUSIC_DIR',     line: 'XDG_MUSIC_DIR=\"$HOME/Music\"',         insertafter: EOF }
    - { regexp: '^XDG_PICTURES_DIR',  line: 'XDG_PICTURES_DIR=\"$HOME/Pictures\"',   insertafter: EOF }
    - { regexp: '^XDG_VIDEOS_DIR',    line: 'XDG_VIDEOS_DIR=\"$HOME/Videos\"',       insertafter: EOF }

- name: english_path | change directory name of japanese in home directory into english
  sudo: yes
  shell: |
    if [ -d {{ ansible_env.HOME }}/{{ item.before }} ]; then mv {{ ansible_env.HOME }}/{{ item.before }} {{ ansible_env.HOME }}/{{ item.after }}; fi
  with_items:
    - { before: 'デスクトップ', after: 'Desktop' }
    - { before: 'ダウンロード', after: 'Download' }
    - { before: 'テンプレート', after: 'Template' }
    - { before: '公開',         after: 'Public' }
    - { before: 'ドキュメント', after: 'Documents' }
    - { before: 'ミュージック', after: 'Music' }
    - { before: 'ピクチャ',     after: 'Pictures' }
    - { before: 'ビデオ',       after: 'Videos' }
