---

- name: ruby | check rbenv is installed
  shell: which rbenv >/dev/null; echo $?
  register: rbenv_stat
  changed_when: false

- include: rbenv_{{ ansible_distribution }}.yml
  when: rbenv_stat.stdout != '0'

- name: ruby | check if ruby is installed
  shell: which ruby >/dev/null; echo $?
  register: ruby_stat
  changed_when: false

- name: ruby | check if specified ruby version is installed
  shell: ruby --version | grep -c {{ RUBY_VERSION }}
  register: ruby_ver
  changed_when: false
  when: ruby_stat.stdout == '0'

- include: ruby_{{ ansible_distribution }}.yml
  when:
    - ruby_stat.stdout != '0'

- include: ruby_extra_libs_{{ ansible_distribution }}.yml
  when:
    - RUBY_INSTALL_EXTRA_LIBS == 'yes'

- include: ruby_open_firewall.yml
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"
