---

# rbenvのイストール
- name: ruby | check rbenv is installed
  shell: which rbenv >/dev/null; echo $?
  register: rbenv_stat
  changed_when: false

- include_tasks: rbenv.yml
  when: rbenv_stat.stdout != '0'

# rubyのインストール
- name: ruby | check if ruby is installed
  stat:
    path: "{{ ansible_env.HOME }}/.rbenv/shims/ruby"
  register: ruby_stat

- name: ruby | check if specified ruby version is installed
  shell: "{{ ansible_env.HOME }}/.rbenv/bin/rbenv versions | grep -c {{ RUBY_VERSION }}"
  register: ruby_ver
  changed_when: false
  failed_when:  false
  when: ruby_stat.stat.exists

- include_tasks: ruby_{{ ansible_distribution }}.yml
  when: ( ruby_stat.stat.exists == False ) or
        ( ruby_ver.stdout == '0' )

- include_tasks: ruby_extra_libs_{{ ansible_distribution }}.yml
  when:
    - RUBY_INSTALL_EXTRA_LIBS|default(true) == true

- include_tasks: ruby_open_firewall.yml
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"

# 汎用gemのインストール
- import_tasks: common_gems.yml
