---

- name: ruby | clone rbenv repository
  git:
    repo: https://github.com/sstephenson/rbenv.git
    dest: "{{ ansible_env.HOME }}/.rbenv"

- name: ruby | clone ruby-build repository
  git:
    repo: https://github.com/sstephenson/ruby-build.git
    dest: "{{ ansible_env.HOME }}/.rbenv/plugins/ruby-build"

- name: ruby | add rbenv path into environment path
  lineinfile:
    dest: "{{ ansible_env.HOME }}/{{ RUBY_SHELL_INIT_FILE }}"
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
    insertafter: "{{ item.insertafter }}"
  with_items:
    - { line: 'export PATH="$HOME/.rbenv/bin:$PATH"', regexp: '^export PATH=\"\$HOME/.rbenv/bin:\$PATH\"', insertafter: EOF }
    - { line: 'eval "$(rbenv init -)"',               regexp: '^eval \"\$\(rbenv init -\)\"',               insertafter: EOF }
