---
# rbenv や rubyに必要なライブラリのインストール

- name: ruby | install required libraries
  become: yes
  apt:
    update_cache: yes
    name:
      - build-essential
      - sqlite3
      - libsqlite3-dev
      - libssl-dev
      - libffi-dev
      - libreadline-dev
      - libyaml-dev
      - zlib1g-dev
