---

- name: ruby | be sure required lib is installed
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - libffi-dev
    - libreadline-dev

- name: ruby | check if ruby installed version
  shell: "{{ ansible_env.HOME }}/.rbenv/bin/rbenv version | cut -d ' ' -f 1 2>/dev/null"
  register: ruby_installed_version
  changed_when: false

- debug:
    var: ruby_installed_version

- name: ruby | be sure ruby is installed
  shell: "{{ ansible_env.HOME }}/.rbenv/bin/rbenv install {{ RUBY_VERSION }}"
#  when: ruby_installed_version.stdout < {{ RUBY_VERSION }}


- name: ruby | update rbenv
  shell: "{{ ansible_env.HOME }}/.rbenv/bin/rbenv rehash"

- name: ruby | specify global configure
  shell: "{{ ansible_env.HOME }}/.rbenv/bin/rbenv global {{ RUBY_VERSION }}"
