---

- include: ruby_required_libs_{{ ansible_distribution }}.yml

- name: ruby | check if ruby installed version
  command: rbenv version | cut -d ' ' -f 1
  changed_when: false
  register: ruby_installed_version

- name: ruby | be sure ruby is installed
  command: rbenv install {{ RUBY_VERSION }}

- name: ruby | update rbenv
  command: rbenv rehash

- name: ruby | specify global configure
  command: rbenv global {{ RUBY_VERSION }}
