name: Ansible Lint

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Lint Ansible Playbook
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: run ansible-lint
        uses: reviewdog/action-ansiblelint@v1
        with:
          github_token: ${{ secrets.github_token }}
