name: Ansible Lint

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint-action@main
        with:
          targets: |
            playbook-devel.yml
          override-deps: |
            ansible-lint==5.1.2
          args: ""
        continue-on-error: true
