name: Ansible Lint

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    name: Lint Ansible Playbook
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: run ansible-lint on reviewdog
        uses: reviewdog/action-ansiblelint@v1
        with:
          github_token: ${{ secrets.github_token }}
          ansiblelint_version: 6.11.0
