name: Security

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  security:
    uses: thaim/actions/.github/workflows/reusable-gha-security.yml@13f286e78bb8d09341e9f9bbeed85058c4113002 # v2.1.0
