name: Security

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  security:
    uses: thaim/actions/.github/workflows/reusable-gha-security.yml@7b7f8e6baefe038585ad0f56061b202160fb84c0 # v2.0.0
