---

- name: Create font dir if not exist
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.fonts"
    state: directory
    mode: "0775"

- name: Install Ricty
  ansible.builtin.include_tasks: ricty.yml
  when: FONT_INSTALL_RICTY|bool

- name: Install Symbola
  ansible.builtin.include_tasks: symbola.yml
  when: FONT_INSTALL_RICTY|bool

- name: Install HackGen
  ansible.builtin.include_tasks: hackgen.yml
