---


- name: Install Ricty
  ansible.builtin.include_tasks: ricty.yml
  when: FONT_INSTALL_RICTY|bool

- name: Install Symbola
  ansible.builtin.include_tasks: symbola.yml
  when: FONT_INSTALL_RICTY|bool

- name: Install HackGen
  ansible.builtin.include_tasks: hackgen.yml
