---

- name: Download symbola fonts
  ansible.builtin.get_url:
    url: https://dn-works.com/wp-content/uploads/2020/UFAS-Fonts/Symbola.zip
    dest: /tmp/symbola.zip
    mode: "0644"

- name: Unarchive zip file
  ansible.builtin.unarchive:
    src: /tmp/symbola.zip
    dest: ~/.fonts/
    remote_src: yes
